[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "<Name>"
version = "<Version#>"
authors = [
    { name="<Author Name>", email="<Author Email>" },
]
description = "<Basic Description>"
requires-python = ">=3.7"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}
